spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6388}
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      routes:
        - id: file_path_route
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: material_path_route
          uri: lb://material-service
          predicates:
            - Path=/materialservice/**
        - id: collection_path_route
          uri: lb://collection-service
          predicates:
            - Path=/collectionservice/**
#      default-filters:
#        - name: Retry
#          args:
#            retries: 3 #需要进行重试的次数
#            statuses: BAD_GATEWAY #返回哪个状态码需要进行重试，返回状态码为5XX进行重试
#        - AddResponseHeader=X-Response-Default-Foo, Default-Bar #增加请求头X-Response-Default-Foo
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 2  #流速 每秒
#            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
#            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
#            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

  feign:
    sentinel:
      enabled: true
    okhttp:
      enabled: true

  jetcache:
    statIntervalMinutes: 1
    areaInCacheName: false
    hidePackages: com.springboot.cloud
    local:
      # 默认永久本地缓存
      default:
        type: caffeine
        keyConvertor: fastjson
    remote:
      # 默认永久的远程缓存
      default:
        type: redis
        keyConvertor: fastjson
        valueEncoder: kryo
        valueDecoder: kryo
        poolConfig:
          minIdle: 5
          maxIdle: 20
          maxTotal: 50
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6388}

  #网关白名单，无需要签权url
  gate:
    ignore:
      authentication:
        startWith: /oauth,/open,/v2/api-docs

  management:
    endpoints:
      web:
        exposure:
          include: '*'

  logging:
    level:
      com.springboot.cloud: debug
      com.jalja.org.spring: debug
    path: logs/
    file:
      max-size: 1GB