version: '3'
services:
  nacos:
    image: nacos/nacos-server
    container_name: mddds-nacos-standalone
    networks:
      - mddds-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
    ports:
      - "8848:8848"